window.SEARCH_WIDGET_CONFIG = {
  "VUE_APP_TAIGER_SEARCH_BASE_ROUTE": "/",
  //"VUE_APP_TAIGER_SEARCH_BASE_URL": "https://dsta-ta-dev-webs.southeastasia.cloudapp.azure.com",
  "VUE_APP_TAIGER_SEARCH_BASE_URL": "https://icrs-prod.taiger.io/intranet/search-gateway2/",
  "VUE_APP_TAIGER_SEARCH_USE_DEV_PROXY": false,
  "VUE_APP_TAIGER_SEARCH_ENABLE_AUTH": false,
  "VUE_APP_TAIGER_SEARCH_IS_AD_AUTH": false,
  "VUE_APP_TAIGER_SEARCH_AD_AUTH_ENDPOINT": "/account/api/user/currentuser",
  "VUE_APP_TAIGER_SEARCH_KPO_INTEGRATION": false,
  "VUE_APP_TAIGER_SEARCH_KPO_ADMIN_UI_URL": "http://localhost:5000",
  "VUE_APP_API_UAA_CONTEXT": "/uaa",
  "VUE_APP_API_SEARCH_SEARCH_CONTEXT": "/search-search",
  "VUE_APP_API_SEARCH_ADMIN_CONTEXT": "/isearch-admin",
  "VUE_APP_API_SEARCH_KM_CONTEXT": "/isearch-km",
  "VUE_APP_TAIGER_SEARCH_ADMIN_ONTOLOGY_URL": "http://is-dev2.taiger.io/ontology-manager/",
  "VUE_APP_TAIGER_AUTH_SEARCH_CONTEXT": "",
  "VUE_APP_TAIGER_SEARCH_IS_SP_AUTH": true,
  "VUE_APP_TAIGER_SEARCH_SP_ENDPOINT": "/",
  "VUE_APP_TAIGER_SEARCH_IS_SP_SEC_KEY": "searchSPKey",
  "VUE_APP_TAIGER_SEARCH_SP_UI_CONFIG_PATH" : "https://taigers.sharepoint.com/_api/web/GetFolderByServerRelativeUrl('/Shared%20Documents')/Files('search-ui.config.json')/$value"
}