window.SEARCH_NER_CONFIG = {
  VUE_APP_TAIGER_NER_BASE_URL: window.SEARCH_WIDGET_CONFIG.VUE_APP_TAIGER_SEARCH_BASE_URL,
  VUE_APP_TAIGER_NER_USE_DEV_PROXY: window.SEARCH_WIDGET_CONFIG.VUE_APP_TAIGER_SEARCH_USE_DEV_PROXY,
  VUE_APP_API_SEARCH_KM_CONTEXT: window.SEARCH_WIDGET_CONFIG.VUE_APP_API_SEARCH_KM_CONTEXT,
};
